import { uid } from './storage';

export const PRESET_WORDS = [
  { id: 'w1', text: '安静' }, { id: 'w2', text: '话多' }, { id: 'w3', text: '直接' },
  { id: 'w4', text: '委婉' }, { id: 'w5', text: '犹豫' }, { id: 'w6', text: '果断' },
  { id: 'w7', text: '慢热' }, { id: 'w8', text: '主动' }, { id: 'w9', text: '被动' },
  { id: 'w10', text: '理性' }, { id: 'w11', text: '感性' }, { id: 'w12', text: '专注' },
  { id: 'w13', text: '发散' }, { id: 'w14', text: '守时' }, { id: 'w15', text: '随性' },
  { id: 'w16', text: '计划' }, { id: 'w17', text: '灵活' }, { id: 'w18', text: '坚持' },
  { id: 'w19', text: '妥协' }, { id: 'w20', text: '倾听' }, { id: 'w21', text: '表达' },
  { id: 'w22', text: '观察' }, { id: 'w23', text: '参与' }, { id: 'w24', text: '独立' },
  { id: 'w25', text: '依赖' }, { id: 'w26', text: '自信' }, { id: 'w27', text: '谨慎' },
  { id: 'w28', text: '幽默' }, { id: 'w29', text: '严肃' }, { id: 'w30', text: '热情' },
  { id: 'w31', text: '冷静' }, { id: 'w32', text: '开放' }, { id: 'w33', text: '保守' },
  { id: 'w34', text: '细腻' }, { id: 'w35', text: '粗犷' }, { id: 'w36', text: '温和' },
  { id: 'w37', text: '锋利' }, { id: 'w38', text: '含蓄' }, { id: 'w39', text: '坦率' },
  { id: 'w40', text: '大胆' }, { id: 'w41', text: '稳定' }, { id: 'w42', text: '多变' },
  { id: 'w43', text: '合群' }, { id: 'w44', text: '独处' }, { id: 'w45', text: '耐心' },
  { id: 'w46', text: '急躁' }, { id: 'w47', text: '包容' }, { id: 'w48', text: '挑剔' },
  { id: 'w49', text: '信任' }, { id: 'w50', text: '怀疑' }, { id: 'w51', text: '支持' },
  { id: 'w52', text: '质疑' }, { id: 'w53', text: '合作' }, { id: 'w54', text: '竞争' },
  { id: 'w55', text: '分享' }, { id: 'w56', text: '保留' }, { id: 'w57', text: '引领' },
  { id: 'w58', text: '跟随' }, { id: 'w59', text: '创新' }, { id: 'w60', text: '传统' },
  { id: 'w61', text: '抽象' }, { id: 'w62', text: '具体' }, { id: 'w63', text: '宏观' },
  { id: 'w64', text: '微观' }, { id: 'w65', text: '长远' }, { id: 'w66', text: '眼前' },
  { id: 'w67', text: '全局' }, { id: 'w68', text: '局部' }, { id: 'w69', text: '过程' },
  { id: 'w70', text: '结果' }, { id: 'w71', text: '情感' }, { id: 'w72', text: '逻辑' },
  { id: 'w73', text: '直觉' }, { id: 'w74', text: '分析' }, { id: 'w75', text: '行动' },
  { id: 'w76', text: '思考' }, { id: 'w77', text: '感受' }, { id: 'w78', text: '判断' },
  { id: 'w79', text: '描述' }, { id: 'w80', text: '回应' },
].map(w => ({ ...w, interpretation_count: Math.floor(Math.random() * 4) + 2 }));

export const PRESET_INTERPRETATIONS = {
  w1: [
    { id: uid(), anon_name: '落叶104', content: '安静不是没有想法，是我更喜欢把想法放在心里慢慢消化。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '山风291', content: '我的安静让很多人觉得我冷漠，但其实我只是不需要用声音填满每一个空间。', created_at: new Date(Date.now() - 86400000 * 3).toISOString() },
    { id: uid(), anon_name: '暮光563', content: '安静是我给自己的礼物，也是我给别人的空间。', created_at: new Date(Date.now() - 86400000 * 6).toISOString() },
  ],
  w2: [
    { id: uid(), anon_name: '晨雾255', content: '我话多是因为我怕沉默。沉默让我觉得我们之间有什么东西断掉了。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '星尘102', content: '我说很多，但真正想说的那句话，往往藏在最后，或者根本没说出口。', created_at: new Date(Date.now() - 86400000 * 4).toISOString() },
    { id: uid(), anon_name: '细雨488', content: '话多是我的方式，我用语言填满空间，这样就不用面对那些说不清楚的感受。', created_at: new Date(Date.now() - 86400000 * 7).toISOString() },
  ],
  w3: [
    { id: uid(), anon_name: '冬雪443', content: '直接让我省了很多弯路，但也让我失去了一些需要被温柔对待的关系。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '远山158', content: '我喜欢直接，因为我不想猜，也不想让别人猜。', created_at: new Date(Date.now() - 86400000 * 4).toISOString() },
    { id: uid(), anon_name: '春泥336', content: '直接有时候是一种勇气，有时候是一种懒得周旋。', created_at: new Date(Date.now() - 86400000 * 7).toISOString() },
  ],
  w4: [
    { id: uid(), anon_name: '林间520', content: '委婉是我保护自己也保护对方的方式，但有时候说了等于没说。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '霜晨204', content: '我委婉是因为我在乎对方的感受，但后来发现对方根本没听懂我在说什么。', created_at: new Date(Date.now() - 86400000 * 5).toISOString() },
  ],
  w5: [
    { id: uid(), anon_name: '暖阳817', content: '犹豫不是软弱，是我在认真对待每一个选择。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '流云388', content: '我犹豫是因为我能看到太多可能性，每一个都有它的道理。', created_at: new Date(Date.now() - 86400000 * 4).toISOString() },
    { id: uid(), anon_name: '溪石671', content: '犹豫让我错过了一些事，但也让我避开了一些坑。', created_at: new Date(Date.now() - 86400000 * 8).toISOString() },
  ],
  w6: [
    { id: uid(), anon_name: '细雨317', content: '果断不是不考虑，是我已经想清楚了，不需要再拖。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '暮光772', content: '我果断，但有时候果断之后会后悔，因为我忽略了一些细节。', created_at: new Date(Date.now() - 86400000 * 5).toISOString() },
  ],
  w7: [
    { id: uid(), anon_name: '浅草091', content: '慢热的人不是不热情，只是需要更多时间才能真正打开自己。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '冬雪443', content: '我慢热，所以很多关系还没开始就结束了。但真正留下来的人，都值得。', created_at: new Date(Date.now() - 86400000 * 4).toISOString() },
    { id: uid(), anon_name: '远山076', content: '慢热是一种自我保护，也是一种筛选机制。', created_at: new Date(Date.now() - 86400000 * 8).toISOString() },
  ],
  w10: [
    { id: uid(), anon_name: '春泥412', content: '理性让我在混乱中保持清醒，但有时候也让我显得冷漠。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '林间688', content: '我理性，但理性不代表没有感受，只是我选择先处理问题再处理情绪。', created_at: new Date(Date.now() - 86400000 * 4).toISOString() },
    { id: uid(), anon_name: '霜晨155', content: '理性是我的盔甲，但有时候我也想脱下来。', created_at: new Date(Date.now() - 86400000 * 7).toISOString() },
  ],
  w11: [
    { id: uid(), anon_name: '暖阳534', content: '感性让我能感受到很多美好，但也让我更容易受伤。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '流云923', content: '我感性，所以我能理解别人的痛苦，但有时候也会把别人的情绪背在自己身上。', created_at: new Date(Date.now() - 86400000 * 5).toISOString() },
    { id: uid(), anon_name: '溪石347', content: '感性不是弱点，是一种更深的感知能力。', created_at: new Date(Date.now() - 86400000 * 9).toISOString() },
  ],
  w18: [
    { id: uid(), anon_name: '晨雾601', content: '坚持是我对自己的承诺，但有时候我也不确定坚持的方向是否正确。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '落叶278', content: '坚持和固执的区别，在于你坚持的那件事值不值得。', created_at: new Date(Date.now() - 86400000 * 4).toISOString() },
    { id: uid(), anon_name: '山风814', content: '我坚持，不是因为不知道放弃，而是因为我知道放弃之后会后悔。', created_at: new Date(Date.now() - 86400000 * 8).toISOString() },
  ],
  w19: [
    { id: uid(), anon_name: '暮光437', content: '妥协不是认输，是我选择了关系比对错更重要。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '浅草762', content: '我妥协太多次了，后来发现有些底线是不能妥协的。', created_at: new Date(Date.now() - 86400000 * 5).toISOString() },
  ],
  w20: [
    { id: uid(), anon_name: '冬雪189', content: '倾听是我给别人最好的礼物，但有时候我也需要有人听我说说话。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '远山523', content: '真正的倾听不是等待说话的机会，而是真的想理解对方。', created_at: new Date(Date.now() - 86400000 * 4).toISOString() },
    { id: uid(), anon_name: '春泥866', content: '我善于倾听，但倾听久了会累，因为你承载了太多别人的重量。', created_at: new Date(Date.now() - 86400000 * 8).toISOString() },
    { id: uid(), anon_name: '林间341', content: '倾听是一种能力，也是一种消耗。', created_at: new Date(Date.now() - 86400000 * 12).toISOString() },
  ],
  w21: [
    { id: uid(), anon_name: '霜晨097', content: '表达对我来说很难，不是因为没有感受，而是找不到准确的词。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '暖阳817', content: '我喜欢表达，因为说出来之后感觉轻了很多。', created_at: new Date(Date.now() - 86400000 * 4).toISOString() },
    { id: uid(), anon_name: '流云388', content: '表达是一种勇气，你要愿意让别人看见你真实的样子。', created_at: new Date(Date.now() - 86400000 * 7).toISOString() },
  ],
  w24: [
    { id: uid(), anon_name: '溪石671', content: '独立让我有安全感，但有时候也让我不知道怎么依靠别人。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '晨雾255', content: '我独立，是因为我不想成为别人的负担。但后来发现，适当依赖也是一种连接。', created_at: new Date(Date.now() - 86400000 * 5).toISOString() },
    { id: uid(), anon_name: '落叶739', content: '独立不是孤独，是我选择了对自己负责。', created_at: new Date(Date.now() - 86400000 * 9).toISOString() },
  ],
  w26: [
    { id: uid(), anon_name: '星尘102', content: '自信不是觉得自己什么都好，而是接受自己的不完美还能继续前进。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '细雨488', content: '我的自信是慢慢建立起来的，每一次做到了一件事，就多一点。', created_at: new Date(Date.now() - 86400000 * 5).toISOString() },
  ],
  w36: [
    { id: uid(), anon_name: '浅草091', content: '温和不是没有立场，是我选择了用平静的方式表达我的立场。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '冬雪443', content: '我温和，但温和不代表可以被随意对待。', created_at: new Date(Date.now() - 86400000 * 4).toISOString() },
    { id: uid(), anon_name: '远山158', content: '温和是一种力量，不是软弱。', created_at: new Date(Date.now() - 86400000 * 8).toISOString() },
    { id: uid(), anon_name: '春泥336', content: '我花了很长时间才明白，温和对待别人的同时，也要温和对待自己。', created_at: new Date(Date.now() - 86400000 * 12).toISOString() },
  ],
  w39: [
    { id: uid(), anon_name: '林间520', content: '坦率让我省了很多心，但也让我在一些需要迂回的场合显得格格不入。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '霜晨204', content: '我坦率，因为我觉得说清楚比让对方猜要好得多。', created_at: new Date(Date.now() - 86400000 * 5).toISOString() },
  ],
  w44: [
    { id: uid(), anon_name: '暖阳534', content: '独处是我充电的方式，不是逃避，是需要。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '流云923', content: '我喜欢独处，但不是不喜欢人，只是需要一些时间和自己在一起。', created_at: new Date(Date.now() - 86400000 * 4).toISOString() },
    { id: uid(), anon_name: '溪石347', content: '独处让我能听见自己真正的声音。', created_at: new Date(Date.now() - 86400000 * 8).toISOString() },
    { id: uid(), anon_name: '晨雾601', content: '独处不是孤独，孤独是你不想一个人但不得不一个人。', created_at: new Date(Date.now() - 86400000 * 12).toISOString() },
  ],
  w45: [
    { id: uid(), anon_name: '落叶278', content: '耐心是我给别人的，但我对自己往往没有那么耐心。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '山风814', content: '耐心不是无限的，它需要被珍惜。', created_at: new Date(Date.now() - 86400000 * 5).toISOString() },
  ],
  w46: [
    { id: uid(), anon_name: '暮光437', content: '我急躁是因为我太在乎结果了。我怕慢下来就会失去什么。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '浅草762', content: '急躁的背后是焦虑。我不是真的想催你，我只是控制不住自己的不安。', created_at: new Date(Date.now() - 86400000 * 4).toISOString() },
    { id: uid(), anon_name: '冬雪189', content: '我知道自己急，但就是停不下来。像一辆刹车失灵的车。', created_at: new Date(Date.now() - 86400000 * 8).toISOString() },
  ],
  w47: [
    { id: uid(), anon_name: '远山523', content: '包容不是没有底线，是我选择了理解而不是评判。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '春泥866', content: '我包容别人，但有时候忘了也要包容自己。', created_at: new Date(Date.now() - 86400000 * 5).toISOString() },
  ],
  w49: [
    { id: uid(), anon_name: '林间341', content: '信任是我给出去最贵重的东西，一旦破碎就很难复原。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '霜晨097', content: '我不是轻易信任的人，但一旦信任了，就是真的信任。', created_at: new Date(Date.now() - 86400000 * 4).toISOString() },
    { id: uid(), anon_name: '暖阳817', content: '信任需要时间建立，但只需要一次就能摧毁。', created_at: new Date(Date.now() - 86400000 * 8).toISOString() },
    { id: uid(), anon_name: '流云388', content: '我选择先信任，因为带着怀疑去相处太累了。', created_at: new Date(Date.now() - 86400000 * 12).toISOString() },
  ],
  w71: [
    { id: uid(), anon_name: '溪石671', content: '情感不是弱点，是我和这个世界连接的方式。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '晨雾255', content: '我有很多情感，但不是每一种都知道怎么表达。', created_at: new Date(Date.now() - 86400000 * 4).toISOString() },
    { id: uid(), anon_name: '落叶739', content: '情感是真实的，即使它有时候让我显得不够理性。', created_at: new Date(Date.now() - 86400000 * 8).toISOString() },
  ],
  w77: [
    { id: uid(), anon_name: '星尘102', content: '感受是最诚实的，它不会骗你，但你要学会听它说话。', created_at: new Date(Date.now() - 86400000).toISOString() },
    { id: uid(), anon_name: '细雨488', content: '我的感受有时候比我的想法更快知道答案。', created_at: new Date(Date.now() - 86400000 * 5).toISOString() },
    { id: uid(), anon_name: '浅草091', content: '允许自己有感受，是我花了很长时间才学会的事。', created_at: new Date(Date.now() - 86400000 * 9).toISOString() },
  ],
};

export const TAG_SIMILAR_MAP = [
  { keywords: ['安静','内敛','不说话'], wordId: 'w1' },
  { keywords: ['话多','爱说话','停不下来'], wordId: 'w2' },
  { keywords: ['直接','直说','坦率'], wordId: 'w3' },
  { keywords: ['委婉','含蓄','拐弯'], wordId: 'w4' },
  { keywords: ['犹豫','不决断','迟疑'], wordId: 'w5' },
  { keywords: ['果断','决断','快决定'], wordId: 'w6' },
  { keywords: ['慢热','不容易亲近','需要时间'], wordId: 'w7' },
  { keywords: ['主动','爱联系','爱发起'], wordId: 'w8' },
  { keywords: ['被动','等待','不主动'], wordId: 'w9' },
  { keywords: ['理性','逻辑','冷静'], wordId: 'w10' },
  { keywords: ['感性','情感','感受型'], wordId: 'w11' },
  { keywords: ['专注','深入','专心'], wordId: 'w12' },
  { keywords: ['坚持','不放弃','坚定'], wordId: 'w18' },
  { keywords: ['妥协','让步','就范'], wordId: 'w19' },
  { keywords: ['倾听','善听','耐心听'], wordId: 'w20' },
  { keywords: ['表达','说出来','善表达'], wordId: 'w21' },
  { keywords: ['独立','自主','不依赖'], wordId: 'w24' },
  { keywords: ['自信','确定','相信自己'], wordId: 'w26' },
  { keywords: ['温和','平和','温柔'], wordId: 'w36' },
  { keywords: ['坦率','直接说','不拐弯'], wordId: 'w39' },
  { keywords: ['独处','一个人','需要空间'], wordId: 'w44' },
  { keywords: ['耐心','不着急','慢慢来'], wordId: 'w45' },
  { keywords: ['急躁','容易急','冲动'], wordId: 'w46' },
  { keywords: ['包容','接受','不计较'], wordId: 'w47' },
  { keywords: ['信任','相信','信赖'], wordId: 'w49' },
  { keywords: ['情感','感情','情绪'], wordId: 'w71' },
  { keywords: ['感受','感知','感觉'], wordId: 'w77' },
];
